
version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pmh
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "aemarquez1993/plan-my-hikes-backend"
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:passsword@db:5432/pmh
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "aemarquez1993/plan-my-hikes-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"