
version: '3'

services:
  backend:
    # env_file:
    #     "./backend/backend.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "aemarquez1993/plan-my-hikes-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "aemarquez1993/plan-my-hikes-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"