
version: '3'

services:
  backend:
    image: "aemarquez1993/plan-my-hikes-backend"
    mem_limit: 128m
    hostname: backend
    environment:
      PORT: ${PORT}
  client:
    restart: always
    mem_limit: 128m
    hostname: client
    image: "aemarquez1993/plan-my-hikes-client"
    environment:
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  nginx:
    restart: always
    depends_on:
        - client
        - backend
    image: "aemarquez1993/plan-my-hikes-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"