const { Pool } = require('pg');

const pool = new Pool({
    host: 'localhost',
    port: 5432, // or your PostgreSQL port number
    database: 'pmh',
    user: 'postgres',
    password: 'password',
  });

async function createRow(data) {
  const query = {
    text: 'INSERT INTO parks (name, route, location, tips, hidden_gem, schedule, best, tough, camping, busy, id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)',
    values: [data.name, data.route, data.location, data.tips, data.gem, data.schedule, data.best, data.tough, data.camping, data.busy, data.id],
  };

  try {
    const result = await pool.query(query);
    console.log(`Created ${result} row(s)`);
  } catch (err) {
    console.error(err);
  }
}


createRow({
    name: "Acadia National Park",
    route: "acadia_national_park",
    location: "Maine, USA",
    tips: "Here are some unique advice and tips for Acadia National Park: Visit during the shoulder seasons (late spring and early fall) to avoid the crowds and enjoy the park when the weather is still pleasant. Get up early to catch the sunrise from Cadillac Mountain, the highest point on the East Coast. This is a popular spot, so arriving early will help you beat the crowds. Take advantage of the park's free shuttle system, which operates on several routes and can help you avoid parking congestion during peak season. Take a break from hiking and explore the park's waterways by kayaking or canoeing. Rentals are available in several locations throughout the park. Go stargazing at night, as Acadia is one of the few places on the East Coast where you can see the Milky Way. Check out the park's ranger-led programs and tours, which include guided hikes, boat trips, and educational programs. Take time to explore the charming nearby towns of Bar Harbor and Southwest Harbor, which offer a variety of restaurants, shops, and galleries. Don't forget to pack layers, as the weather can change quickly in Acadia, and bring bug spray during the summer months.",
    gem: "Acadia National Park has many hidden gems that are worth exploring. One of these hidden gems is the Wonderland Trail, a scenic coastal hiking trail located on the quiet western side of Mount Desert Island. The Wonderland Trail is a relatively easy 1.4-mile hike that winds through a picturesque forest and along the rocky coast of Maine. The trail offers stunning views of the ocean, small islands, and the rugged coastline. It also has several small beaches and coves that are perfect for a picnic or a dip in the ocean. What makes the Wonderland Trail a hidden gem is that it is often overlooked by visitors who focus on the more popular hikes and attractions in the park. As a result, you can enjoy a peaceful and uncrowded hike and experience the natural beauty of Acadia National Park in a tranquil and serene setting.",
    schedule: "Sure, here's a detailed itinerary for a 6-night trip to Acadia National Park: Day 1: Arrive at the park in the afternoon and check-in to your accommodation. Enter the park through the Hulls Cove Visitor Center. Overnight in Bar Harbor with parking at the accommodation. Day 2: Hike the Cadillac Mountain South Ridge Trail (3.5 miles round trip) to the summit of Cadillac Mountain, which offers stunning views of the sunrise and sunset. Overnight in Bar Harbor with parking at the trailhead. Day 3: Explore the carriage roads, a network of scenic gravel paths that wind through the park and offer opportunities for biking or walking. Overnight in Bar Harbor with parking at the trailhead. Day 4: Hike the Precipice Trail (2.5 miles round trip), a challenging but rewarding trail that features iron rungs and ladders on steep cliffs. Overnight in Bar Harbor with parking at the trailhead. Day 5: Take a guided tour or hike the Jordan Pond Path (3.3 miles round trip) and enjoy the beautiful views of the pond and surrounding mountains. Overnight in Southwest Harbor with parking at the trailhead. Day 6: Hike the Beehive Trail (1.4 miles round trip), another challenging trail with ladders and iron rungs on steep cliffs, followed by a visit to Sand Beach. Overnight in Southwest Harbor with parking at the trailhead. Day 7: Depart from the park in the morning.",
    best: "Acadia National Park is a stunning destination with a wide range of experiences to offer. One of the single best experiences of Acadia National Park is hiking up to the summit of Cadillac Mountain, which is the highest peak on the East Coast of the United States. Cadillac Mountain offers incredible views of the surrounding landscape, including the Atlantic Ocean, neighboring islands, and the rolling hills of Acadia National Park. The hike up to the summit is relatively easy and takes about an hour, with well-maintained trails and plenty of signs along the way. The sunrise from Cadillac Mountain is particularly breathtaking and is known as one of the earliest sunrises in the United States due to its location on the East Coast. Watching the sunrise from the summit is a truly unforgettable experience, and it's no wonder that this is a popular activity for visitors to Acadia National Park.",
    tough: "One of the toughest hikes in Acadia National Park that is lesser-known is the Sargent Mountain Loop Trail. This 5.5-mile loop hike is rated as difficult due to its steep elevation gain and rugged terrain. The trailhead is located on the Park Loop Road near the Jordan Pond House. The hike begins with a steep climb up the Sargent South Ridge Trail, which offers stunning views of Jordan Pond and the surrounding mountains. The trail then continues along the ridge, with several steep ascents and descents, before reaching the summit of Sargent Mountain, the second-highest peak in the park at 1,373 feet. The summit offers panoramic views of the park and the coast, making it a popular spot for hikers. The descent follows the Sargent East Cliffs Trail, which features rocky terrain and steep sections with iron rungs and ladders. The final stretch of the hike follows the Jordan Pond Path back to the trailhead. The entire hike takes around 4-5 hours to complete and requires good physical fitness and endurance, as well as some scrambling and rock climbing skills. However, the breathtaking views and sense of accomplishment make it a rewarding experience for those who are up for the challenge.",
    camping: "One of the best camping trails in Acadia National Park is the Sargent Mountain Loop Trail. The trailhead for this 5.5-mile loop hike is located on the Park Loop Road near the Jordan Pond House, where there is a large parking lot available for hikers. Camping is available at the Sargent Mountain South Ridge Campsite, which is located along the trail near the summit of Sargent Mountain. The campsite is open year-round and can accommodate up to 6 people, with a maximum stay of 3 nights. A permit is required for camping and can be obtained from the park rangers or online in advance. The Sargent Mountain Loop Trail is a challenging hike, with steep elevation gain and rugged terrain, but it rewards hikers with stunning views of Jordan Pond and the surrounding mountains. The Sargent Mountain South Ridge Campsite is located near the summit of Sargent Mountain, offering panoramic views of the park and the coast. This makes it a great spot for camping, as you can wake up to beautiful views and enjoy the peacefulness of being on the mountain. The hike takes around 4-5 hours to complete, and it is recommended that hikers start early to allow for plenty of time to reach the campsite and set up camp before dark. Overall, this trail is a great option for experienced hikers who want to combine a challenging hike with a unique camping experience in Acadia National Park.",
    busy: "The most crowded months to visit Acadia National Park are typically July, August, and September. During these months, the park sees a high volume of visitors, particularly on weekends and holidays. The weather is generally mild, and many visitors come to enjoy the park's scenic beauty, hiking trails, and outdoor activities. As a result, popular areas such as the Park Loop Road, Cadillac Mountain, and Jordan Pond can become quite crowded. Visitors who prefer a quieter experience may want to consider visiting the park during the shoulder seasons of May, June, and October when the crowds are smaller, and the weather is still pleasant.",
    id: 3  
});
