const { Pool } = require('pg');

const pool = new Pool({
    host: 'localhost',
    port: 5432, // or your PostgreSQL port number
    database: 'pmh',
    user: 'postgres',
    password: 'password',
  });

async function createRow(data) {
  const query = {
    text: 'INSERT INTO parks (name, route, location, tips, gem, schedule, best, tough, camping, busy, id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)',
    values: [data.name, data.route, data.location, data.tips, data.gem, data.schedule, data.best, data.tough, data.camping, data.busy, data.id],
  };

  try {
    const result = await pool.query(query);
    console.log(`Created ${result.rowCount} row(s)`);
  } catch (err) {
    console.error(err);
  }
}


createRow({
    name: "Big Bend National Park",
    route: "big_bend_national_park",
    location: "Texas, USA",
    tips: "Big Bend National Park is a vast and beautiful area with a variety of landscapes, including mountains, canyons, and desert. Here are some unique advice and tips to help you make the most of your visit: Plan your trip in advance: Big Bend National Park covers over 800,000 acres, so it's a good idea to plan your trip in advance. Research the park's different regions, activities, and trails to create an itinerary that suits your interests. Visit in the offseason: Big Bend can get very crowded during peak season, which runs from November to April. Consider visiting in the offseason, such as summer when it is hot, but fewer visitors come. Explore the park's backcountry: Big Bend's backcountry is a great way to escape the crowds and experience the park's natural beauty up close. You can explore it by hiking or backpacking, but make sure to obtain a backcountry permit from the park's visitor center before heading out. Take advantage of ranger-led activities: The park offers a range of ranger-led activities, such as guided hikes and stargazing programs. These programs can provide you with a deeper understanding of the park's ecology and history. Bring plenty of water: The desert environment of Big Bend can be hot and dry, so be sure to bring plenty of water, especially if you plan to hike or explore the backcountry. Watch the wildlife: Big Bend is home to a variety of wildlife, including black bears, mountain lions, and rattlesnakes. Be sure to observe them from a safe distance and never approach or feed them. Look up at night: Big Bend is a designated International Dark Sky Park, which means it has minimal light pollution and offers stunning views of the night sky. Be sure to look up at night and stargaze during your visit. Respect the park's rules and regulations: Finally, it's important to respect the park's rules and regulations, such as staying on designated trails, disposing of trash properly, and leaving the natural environment undisturbed.",
    gem: "A hidden gem of Big Bend National Park is the Hot Springs Historic Trail. This short, easy trail leads to the remains of a historic hot springs resort that was built in the early 1900s. Along the way, hikers can see the ruins of the old resort buildings, including the bathhouse and a hotel. At the end of the trail, there is a natural hot springs pool where visitors can soak in the warm, mineral-rich water. The pool is located right on the banks of the Rio Grande, offering stunning views of the river and the surrounding mountains. This is a great spot to relax and take in the beauty of the park. The trail is less crowded than some of the other popular hikes in the park, making it a peaceful and serene experience.",
    schedule: "Here is a 6-night itinerary for Big Bend National Park: Day 1: Arrival in Big Bend National Park. Check-in at Chisos Mountains Lodge (or any other lodging option of your choice). Visit the Panther Junction Visitor Center to obtain park maps, guidebooks, and information about park activities and ranger-led programs. Watch the sunset at the Window View Trail (0.3 miles round trip). Day 2: Hike the Lost Mine Trail (4.8 miles round trip) in the morning, offering breathtaking views of the Chisos Mountains. Drive to the Santa Elena Canyon Overlook (1.1 miles round trip) for an afternoon hike along the Rio Grande riverbank. Overnight camping at Chisos Basin Campground. Day 3: Hike the South Rim Trail (12 miles round trip) in the Chisos Mountains, known for its panoramic views of the park. Overnight camping at Chisos Basin Campground. Day 4: Drive to the Boquillas Canyon Trailhead for a scenic drive to the Rio Grande village. Cross the Rio Grande into Boquillas, Mexico, for a cultural experience and lunch at the local restaurant. Drive back to the park and hike the Hot Springs Historic Trail (1.5 miles round trip) and soak in the hot springs. Overnight camping at Rio Grande Village Campground. Day 5: Explore the park's eastern section by driving to the Homer Wilson Ranch Trailhead for a morning hike on the Marufo Vega Trail (6.5 miles round trip). Visit the Fossil Discovery Exhibit to see prehistoric fossils and learn about the park's geology. Watch the sunset at the Sotol Vista Overlook. Overnight camping at Rio Grande Village Campground. Day 6: Visit the historic Terlingua Ghost Town for a cultural experience and lunch at the local restaurant. Hike the Chimneys Trail (4.8 miles round trip) in the afternoon, offering unique rock formations and views of the surrounding desert. Overnight at the Chisos Mountains Lodge. Day 7: Depart from Big Bend National Park. Entrance fees for the park are $30 per vehicle and are valid for 7 days. The parking areas for the various trails and sites are well-marked and easily accessible. However, it is recommended to arrive early in the morning to secure a parking spot, especially during peak season. Please note that the park is quite large and there are many other hikes and activities to explore, so this itinerary is just a starting point for your trip. It is recommended to check the park's website and speak with rangers to plan your trip and ensure a safe and enjoyable experience.",
    best: "One of the single best experiences of Big Bend National Park is hiking the South Rim Trail. This 12-mile round-trip trail offers stunning panoramic views of the Chisos Mountains and the surrounding desert landscape. Hikers can expect to see a variety of wildlife and plants, including cacti and the occasional bear or mountain lion. The trail is challenging and steep in some sections, but the breathtaking views make it well worth the effort. It is recommended to start the hike early in the morning to avoid the heat of the day and to bring plenty of water and snacks.",
    tough: "One of the toughest hikes in Big Bend National Park that is lesser known is the Marufo Vega Trail. This trail is a 14.5-mile loop that usually takes around 7-9 hours to complete. The Marufo Vega Trail is a demanding hike due to the rugged terrain and lack of water sources along the trail. The trail starts at the Marufo Vega Trailhead, located at the western end of the park, and follows a steep, rocky path up to the ridgeline of the Marufo Vega Mountains. The trail then descends down into a narrow canyon and follows the course of the Rio Grande River, offering stunning views of the surrounding canyon walls and the river itself. The trail then climbs back up to the ridgeline before descending again to the trailhead. The challenging aspects of the Marufo Vega Trail include its length, elevation gain, and the rocky terrain. The trail is remote, and hikers should be prepared to carry plenty of water and snacks, as there are no reliable water sources along the trail. Additionally, hikers should be aware that the trail can be difficult to follow in some areas, so it's important to bring a map and compass or GPS device. The trail is also exposed to the sun, making it important to wear appropriate sun protection. Overall, the Marufo Vega Trail is a challenging and rewarding hike for experienced hikers who are looking for a lesser-known trail in Big Bend National Park. Proper planning, preparation, and physical fitness are essential for a successful hike.",
    camping: "One of the best camping trails in Big Bend National Park is the South Rim Trail in the Chisos Mountains. The trailhead for the South Rim Trail is located at the Chisos Basin Visitor Center, which has ample parking. While a reservation is not required for backcountry camping in Big Bend, it is recommended to obtain a permit at the visitor center before beginning your hike. The South Rim Trail is a strenuous 12-mile round-trip hike that takes you to the highest point in the Chisos Mountains, offering breathtaking views of the park and surrounding desert. Along the way, you'll pass through lush forests, high mountain meadows, and rocky terrain. There are several designated backcountry campsites along the trail, including Boot Canyon, Juniper Flat, and South Rim. These campsites require a reservation and have a limited capacity, so it's important to plan ahead. The South Rim Trail is a great option for camping because it offers a true wilderness experience with stunning views and peaceful solitude. Plus, camping in the Chisos Mountains allows you to escape the heat and enjoy cooler temperatures, even in the summer. Just be sure to bring plenty of water, food, and appropriate gear, as the trail is remote and challenging.",
    busy: "The most crowded months to visit Big Bend National Park are typically from mid-February through May, and from mid-October through December. These periods coincide with the spring break, Easter, Thanksgiving, and Christmas holidays, as well as with cooler temperatures and wildflower blooms. However, the park can still be busy during other times of the year, especially on weekends and holidays. It's always a good idea to check the park's website and plan ahead to avoid crowds and ensure the best possible experience.",
    id: 2  
});