CREATE TABLE parks (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  location VARCHAR(255) NOT NULL,
  route VARCHAR(255) NOT NULL UNIQUE,
  tips TEXT NOT NULL,
  best TEXT NOT NULL,
  hidden_gem TEXT NOT NULL,
  schedule TEXT NOT NULL,
  camping TEXT NOT NULL,
  busy TEXT NOT NULL,
  tough TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);